{
 "title": "PVS",
 "description": "Home solar system",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System current power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"PVS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PVS6\")\n  |> filter(fn: (r) => r[\"device\"] == \"system\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kW\")\n  |> last()"
    }
   ]
  },
  {
   "title": "System 24hr energy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "data = from(bucket: \"PVS\")\n    |> range(start: -25h)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"PVS6\")\n    |> filter(fn: (r) => r[\"device\"] == \"system\")\n    |> filter(fn: (r) => r[\"_field\"] == \"kWh\")\n\ncurrentData = data\n    |> last()\n\npastData = data\n    |> range(start: -25h, stop: -24h)\n    |> timeShift(duration: 24h) // Shift timestamps forward by 24 hours\n    |> last()\n\njoinedData = join(tables: {current: currentData, past: pastData}, on: [\"device\"])\n\nresult = joinedData\n    |> map(fn: (r) => ({\n        _time: r._time_current,\n        _value: r._value_current - r._value_past,\n        _field: \"difference\" // Rename the field to reflect the difference\n    }))\n    |> yield(name: \"difference\")\n"
    }
   ]
  },
  {
   "title": "System lifetime energy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"PVS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PVS6\")\n  |> filter(fn: (r) => r[\"device\"] == \"system\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kWh\")\n  |> last()"
    }
   ]
  },
  {
   "title": "System power history",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "query": "from(bucket: \"PVS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PVS6\")\n  |> filter(fn: (r) => r[\"device\"] == \"system\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kW\")\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Panels", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Panel current power production",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"strings\"\n\nfrom(bucket: \"PVS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PVS6\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kW\")\n  |> map(fn: (r) => ({\n        r with\n        prefix_value: strings.substring(v: r.device, start: 0, end: 8)\n    }))\n  |> filter(fn: (r) => r.prefix_value == \"inverter\")\n  |> last()\n  |> group(columns: [], mode: \"by\")\n  |> pivot(rowKey: [\"_field\"], columnKey: [\"device\"], valueColumn: \"_value\")\n"
    }
   ]
  },
  {
   "title": "Panel lifetime energy production",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"strings\"\n\nfrom(bucket: \"PVS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PVS6\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kWh\")\n  |> map(fn: (r) => ({\n        r with\n        prefix_value: strings.substring(v: r.device, start: 0, end: 8)\n    }))\n  |> filter(fn: (r) => r.prefix_value == \"inverter\")\n  |> last()\n  |> group(columns: [], mode: \"by\")\n  |> pivot(rowKey: [\"_field\"], columnKey: [\"device\"], valueColumn: \"_value\")\n"
    }
   ]
  },
  {
   "title": "Panel power history",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "query": "from(bucket: \"PVS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PVS6\")\n  |> filter(fn: (r) => r[\"device\"] == \"inverter-00\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kW\")\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"PVS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PVS6\")\n  |> filter(fn: (r) => r[\"device\"] == \"inverter-01\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kW\")\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"PVS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PVS6\")\n  |> filter(fn: (r) => r[\"device\"] == \"inverter-02\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kW\")\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"PVS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PVS6\")\n  |> filter(fn: (r) => r[\"device\"] == \"inverter-03\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kW\")\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"PVS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PVS6\")\n  |> filter(fn: (r) => r[\"device\"] == \"inverter-04\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kW\")\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"PVS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PVS6\")\n  |> filter(fn: (r) => r[\"device\"] == \"inverter-05\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kW\")\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"PVS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PVS6\")\n  |> filter(fn: (r) => r[\"device\"] == \"inverter-06\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kW\")\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"PVS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PVS6\")\n  |> filter(fn: (r) => r[\"device\"] == \"inverter-07\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kW\")\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"PVS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PVS6\")\n  |> filter(fn: (r) => r[\"device\"] == \"inverter-08\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kW\")\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"PVS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PVS6\")\n  |> filter(fn: (r) => r[\"device\"] == \"inverter-09\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kW\")\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"PVS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PVS6\")\n  |> filter(fn: (r) => r[\"device\"] == \"inverter-10\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kW\")\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"PVS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PVS6\")\n  |> filter(fn: (r) => r[\"device\"] == \"inverter-11\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kW\")\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"PVS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PVS6\")\n  |> filter(fn: (r) => r[\"device\"] == \"inverter-12\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kW\")\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"PVS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PVS6\")\n  |> filter(fn: (r) => r[\"device\"] == \"inverter-13\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kW\")\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"PVS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PVS6\")\n  |> filter(fn: (r) => r[\"device\"] == \"inverter-14\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kW\")\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"PVS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PVS6\")\n  |> filter(fn: (r) => r[\"device\"] == \"inverter-15\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kW\")\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Panel current temperature",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "import \"strings\"\n\nfrom(bucket: \"PVS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PVS6\")\n  |> filter(fn: (r) => r[\"_field\"] == \"C\")\n  |> map(fn: (r) => ({\n        r with\n        prefix_value: strings.substring(v: r.device, start: 0, end: 8)\n    }))\n  |> filter(fn: (r) => r.prefix_value == \"inverter\")\n  |> last()\n  |> group(columns: [], mode: \"by\")\n  |> pivot(rowKey: [\"_field\"], columnKey: [\"device\"], valueColumn: \"_value\")\n"
    }
   ]
  }
 ]
}